pipeline {
    agent any 
    
    environment{
        OPENAI_API_KEY = credentials('OPENAI_API_KEY')
        GITHUB_TOKEN = credentials('GITHUB_TOKEN')
    }


    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    bat 'npm install'
                }
            }
        }
        stage('Compile TypeScript') {
            steps {
                script {
                    bat 'npx tsc' 
                }
            }
        }
        stage('Run Application') {
            steps {
                script {
                    bat 'node dist/index.js'
                }
            }
        }
    }
}