pipeline {
    agent any 
    
    environment{
        OPENAI_API_KEY = credentials('OPENAI_API_KEY')
        GITHUB_TOKEN = credentials('GITHUB_TOKEN')
    }

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    bat 'npm install'
                }
            }
        }
        stage('Run PR Review Bot') {
            steps {
                script {
                    bat 'npm run start'
                }
            }
        }
    }
}